import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import LogoutButton from "@/components/LogoutButton";
import { auth } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body className="flex flex-col h-dvh overflow-y-hidden">
        <Navbar
          brand={{ href: "/", display: "Fullstack Starter" }}
          links={session ? [{ href: "/clients", display: "Clients" }] : []}
          action={session ? <LogoutButton /> : undefined}
        />
        {children}
      </body>
    </html>
  );
}
